/**
 * Action Intents.
 */
export const INTENTS = {
	INTENT: 'INTENT',
	USER_UPDATE_FULL_NAME: 'USER_UPDATE_FULL_NAME',
	USER_DELETE_ACCOUNT: 'USER_DELETE_ACCOUNT',
	ADD_NEW_TASK: 'ADD_NEW_TASK',
} as const
